# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='tipo_bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BODEGA', to='laboratorio.Tipo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_tipo_unidadmedida', to='laboratorio.Tipo'),
        ),
        migrations.AlterField(
            model_name='productosenbodega',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodbod_tipo_unidadmedida', to='laboratorio.Tipo'),
        ),
        migrations.AlterField(
            model_name='transaccioninventario',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='STATUSTRX', to='laboratorio.Tipo'),
        ),
        migrations.AlterField(
            model_name='transaccioninventario',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TIPOTRX', to='laboratorio.Tipo'),
        ),
        migrations.AlterField(
            model_name='transaccioninventario',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trx_tipo_unidadmedida', to='laboratorio.Tipo'),
        ),
    ]
