# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 21:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, null=True, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('valorUnitario', models.DecimalField(decimal_places=4, max_digits=7)),
                ('unidadesExistentes', models.IntegerField()),
                ('clasificacion', models.CharField(choices=[('Materiales Vivos', (('Bac', 'Bacterias'), ('Hon', 'Hongos'))), ('Medios de Cultivo', (('Glu', 'Glucosa'), ('Fru', 'Fructuosa'), ('Tri', 'Triptona'), ('Pep', 'Peptona'))), ('Micronutrientes', (('Fe', 'Hierro'), ('Mg', 'Magnesio'), ('P', 'Fosforo'))), ('Manipulacion ADN y Proteinas', (('Pri', 'Primers'), ('Kem', 'Kits de extraccion metagenomica'), ('KeADN', 'Kits de extraccion ADN aislado'), ('Pup', 'Purificador de proteinas'), ('Enr', 'Enzimas de restriccion'), ('Pro', 'Proteasas'))), ('Otros', 'Moleculas genericas')], max_length=35)),
                ('imageFile', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosEnBodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(null=True)),
                ('seccion', models.IntegerField(null=True)),
                ('cantidad', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='limite',
        ),
        migrations.AddField(
            model_name='bodega',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='fecha_actualizacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='fecha_creacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='niveles',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='secciones',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='serial',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='temperatura_media',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='temperatura_minima',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='ubicacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bodega',
            name='usuario_actualizacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='usuario_creacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productosenbodega',
            name='bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Bodega'),
        ),
        migrations.AddField(
            model_name='productosenbodega',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Producto'),
        ),
        migrations.AddField(
            model_name='productosenbodega',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Tipo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Tipo'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='tipo_bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Tipo'),
        ),
    ]
