# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Tipo'),
        ),
    ]
