# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_transaccioninventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, null=True, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField(null=True)),
                ('estado', models.CharField(max_length=50)),
                ('asignado', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoProtocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('cantidadUtilizada', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.BigIntegerField(null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField(null=True)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='productoprotocolo',
            name='protocolo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Protocolo'),
        ),
        migrations.AddField(
            model_name='experimento',
            name='protocolo',
            field=models.ManyToManyField(to='laboratorio.Protocolo'),
        ),
    ]
