# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 03:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_auto_20170316_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='cupo_bandeja',
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='limite',
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='numero_bandejas',
        ),
        migrations.AddField(
            model_name='bodega',
            name='niveles',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='secciones',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='ubicacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='fecha_creacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='temperatura_media',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='temperatura_minima',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='usuario_actualizacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='usuario_creacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tipobodega',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
