# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_auto_20170316_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imageFile',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='tipobodega',
            name='nombre',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
