# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_detalleorden_ordenpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosenbodega',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
    ]
