# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_detalleorden_ordenpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_media_uso',
            field=models.DecimalField(decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='frecuencia_media_uso',
            field=models.CharField(choices=[('Continua', 'Muchas veces al dia'), ('Frecuente', 'Al menos 1 vez al dia'), ('Ocasional', 'Al menos 1 vez a la semana'), ('PocoUsual', 'Al menos 1 vez al mes'), ('Rara', 'Unas pocas veces al anio'), ('MuyRara', 'Al menos 1 vez al anio'), ('NA', 'NA')], default='', max_length=26),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='frecuencia_minima_uso',
            field=models.CharField(choices=[('Continua', 'Muchas veces al dia'), ('Frecuente', 'Al menos 1 vez al dia'), ('Ocasional', 'Al menos 1 vez a la semana'), ('PocoUsual', 'Al menos 1 vez al mes'), ('Rara', 'Unas pocas veces al anio'), ('MuyRara', 'Al menos 1 vez al anio'), ('NA', 'NA')], default='', max_length=26),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='tiempo_reaprovisionamiento',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
