# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0006_auto_20170411_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='punto_pedido',
            field=models.DecimalField(decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_seguridad',
            field=models.DecimalField(decimal_places=8, max_digits=15, null=True),
        ),
    ]
