# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0006_productosenbodega_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.OrdenPedido'),
        ),
    ]
