# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0008_auto_20170419_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(null=True)),
                ('orden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op_comentarios', to='laboratorio.OrdenPedido')),
            ],
        ),
    ]
