# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 19:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0009_comentarioorden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(null=True)),
                ('seccion', models.IntegerField(null=True)),
                ('diferencia_cantidad', models.IntegerField(null=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Bodega')),
            ],
        ),
        migrations.CreateModel(
            name='ConteoInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_cambio_estado', models.DateTimeField(null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='STATUS_CONTEO', to='laboratorio.Tipo')),
                ('tipo_inventario_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TIPO_INVENTARIO_PRODUCTO_CONTEO', to='laboratorio.Tipo')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion_conteo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(null=True)),
                ('seccion', models.IntegerField(null=True)),
                ('cantidad_contada', models.IntegerField(null=True)),
                ('cantidad_fisica', models.IntegerField(null=True)),
                ('diferencia_cantidad', models.IntegerField(null=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Bodega')),
                ('conteoinventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.ConteoInventario')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='STATUS_CONTEO_DETALLE', to='laboratorio.Tipo')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_inventario_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TIPO_INVENTARIO_PRODUCTO', to='laboratorio.Tipo'),
        ),
        migrations.AddField(
            model_name='detalleproductos',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Producto'),
        ),
        migrations.AddField(
            model_name='detalleproductos',
            name='productosenbodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.ProductosEnBodega'),
        ),
        migrations.AddField(
            model_name='detalleproductos',
            name='tipo_diferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_diferencia_detalle', to='laboratorio.Tipo'),
        ),
        migrations.AddField(
            model_name='detalleproductos',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_unidadmedida_detalle', to='laboratorio.Tipo'),
        ),
        migrations.AddField(
            model_name='detalleproductos',
            name='usuario_conteo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion_detalle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ajuste',
            name='detalle_productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.DetalleProductos'),
        ),
        migrations.AddField(
            model_name='ajuste',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Producto'),
        ),
        migrations.AddField(
            model_name='ajuste',
            name='productosenbodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.ProductosEnBodega'),
        ),
        migrations.AddField(
            model_name='ajuste',
            name='tipo_diferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_diferencia_ajuste', to='laboratorio.Tipo'),
        ),
        migrations.AddField(
            model_name='ajuste',
            name='transaccion_inventario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='do_transaccion_ajuste', to='laboratorio.TransaccionInventario'),
        ),
    ]
