# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0010_auto_20170509_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_producto_conteo',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
