# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0011_producto_tipo_producto_conteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajuste',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='do_estado_ajuste', to='laboratorio.Tipo'),
        ),
    ]
