# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0012_ajuste_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproductos',
            name='bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Bodega'),
        ),
        migrations.AlterField(
            model_name='detalleproductos',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='STATUS_CONTEO_DETALLE', to='laboratorio.Tipo'),
        ),
        migrations.AlterField(
            model_name='detalleproductos',
            name='tipo_diferencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_diferencia_detalle', to='laboratorio.Tipo'),
        ),
    ]
