# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0013_auto_20170515_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoReposicionPendiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Producto')),
            ],
        ),
    ]
