# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0014_productoreposicionpendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoreposicionpendiente',
            name='detalle_orden_guardada',
            field=models.BooleanField(default=False),
        ),
    ]
